theme: jekyll-theme-minimal
title: Monique Wan
description: Associate Professor  
Department of Economics  
Hong Kong Baptist University  
show_downloads: false
navigation:
  - title: Reseearch
    url: research.md
  - title: Teaching
    url: teaching.md



