theme: jekyll-theme-minimal
title: Monique S.K. Wan
description: <img src = "Dr. Monique Shui-Ki Wan 2023.jpg" width = "200" />
navigation:
  - title: Home
    url: /
  - title: Research
    url: research
  - title: Teaching
    url: teaching
