theme: jekyll-theme-minimal
title: Monique S.K. Wan
description: <img src = "hkbu.png" width = "100"/>
navigation:
  - title: Home
    url: /
  - title: Research
    url: research
  - title: Teaching
    url: teaching
