theme: jekyll-theme-minimal
title: Monique Wan
description: Associate Professor 
\n Department of Economics 
\n Hong Kong Baptist University
navigation:
  - title: Home
    url: /
  - title: Research
    url: research
